
about :

  name : 'wTesting'
  description : 'Framework for convenient unit testing. Testing provides the intuitive interface, simple tests structure, asynchronous code handling mechanism, colorful report, verbosity control and more. Use the module to get free of routines which can be automated.'
  version : '1.1.0'
  enabled : 1
  interpreters :
  - njs >= 10.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - testing
  - unit test
  - functional test
  - wTools
  license : MIT
  author : 'Kostiantyn Wandalen <wanalen@01.school>'
  contributors :
  - 'Kostiantyn Wandalen <wanalen@01.school>'
  - 'Volodymyr M. <volodymyr.migdal@gmail.com>'
  - 'Dmytro Kryvoruchko <dm.vict.kr@gmail.com>'
  npm.name : 'wTesting'
  npm.scripts :
    test : 'wtest .run proto/**'
    wtest : 'node proto/wtools/atop/testing/entry/ExecUnrestricted'
    single-process-wtest : 'node proto/wtools/atop/testing/entry/Exec'
    debug-wtest : 'node proto/wtools/atop/testing/entry/ExecDebug'
    tst : 'node proto/wtools/atop/testing/entry/ExecUnrestricted'
    single-process-tst : 'node proto/wtools/atop/testing/entry/Exec'
    debug-tst : 'node proto/wtools/atop/testing/entry/ExecDebug'
  npm.bin :
    wtest : 'proto/wtools/atop/testing/entry/ExecUnrestricted'
    single-process-wtest : 'proto/wtools/atop/testing/entry/Exec'
    debug-wtest : 'proto/wtools/atop/testing/entry/ExecDebug'
    tst : 'proto/wtools/atop/testing/entry/ExecUnrestricted'
    single-process-tst : 'proto/wtools/atop/testing/entry/Exec'
    debug-tst : 'proto/wtools/atop/testing/entry/ExecDebug'

path :

  repository : git+https:///github.com/Wandalen/wTesting.git
  origins :
   - git+https:///github.com/Wandalen/wTesting.git
   - npm:///wTesting
  bugtracker : https:///github.com/Wandalen/wTesting/issues

step :

  proto.export :
    inherit : module.export
    export : path::export
    tar : 0
    criterion :
      content : 'proto'

  doc.export :
    inherit : module.export
    export : path::doc
    tar : 0
    criterion :
      content : 'doc'

  npm.export :
    inherit : module.export
    export : out.npm
    tar : 0
    criterion :
      content : 'npm'

  npm.publish :
    shell : npm publish

build :

  proto.export :
    criterion :
      content : 'proto'
      export : 1
    steps :
      # - build::debug.raw
      - step::proto.export

  doc.export :
    criterion :
      content : 'doc'
      export : 1
    steps :
      # - build::debug.raw
      - step::doc.export

  npm.export :
    criterion :
      content : 'npm'
      export : 1
    steps :
      # - build::debug.raw
      # - step::npm.export
      - step::npm.publish

  export :

    criterion :
      default : 1
      export : 1
    steps :
      # - build::npm
      - build::proto.export
      # - build::doc.export
