submodule:
  wConsequence:
    path: 'npm:///wConsequence'
    enabled: 0
  wCopyable:
    path: 'npm:///wCopyable'
    enabled: 0
  wFiles:
    path: 'npm:///wFiles'
    enabled: 0
  wLogger:
    path: 'npm:///wLogger'
    enabled: 0
  wProto:
    path: 'npm:///wProto'
    enabled: 0
  wTools:
    path: 'npm:///wTools'
    enabled: 0
  wComparator:
    path: 'npm:///wcomparator'
    enabled: 0
  wExternalFundamentals:
    path: 'npm:///wexternalfundamentals'
    enabled: 0
  wCommandsAggregator:
    path: 'npm:///wcommandsaggregator'
    enabled: 0
  wInstancing:
    path: 'npm:///winstancing'
    enabled: 0
  wLooker:
    path: 'npm:///wlooker'
    enabled: 0
  wSelector:
    path: 'npm:///wselector'
    enabled: 0
  wprocesswatcher:
    path: 'npm:///wprocesswatcher'
    enabled: 0
  wEventHandler:
    path: 'npm:///wEventHandler'
    enabled: 0
    criterion:
      optional: 1
  wTesting:
    path: 'hd://.'
    enabled: 0
    criterion:
      development: 1
  electron:
    path: 'npm:///electron#11.3.0'
    enabled: 0
    criterion:
      development: 1
  spectron:
    path: 'npm:///spectron#13.0.0'
    enabled: 0
    criterion:
      development: 1
  puppeteer:
    path: 'npm:///puppeteer#5.5.0'
    enabled: 0
    criterion:
      development: 1
  eslint:
    path: 'npm:///eslint#7.1.0'
    enabled: 0
    criterion:
      development: 1
path:
  in: .
  out: out
  temp:
    - 'path::out'
    - package-lock.json
    - package.json
    - node_modules
  proto: ./proto
  export: '{path::proto}/**'
  doc: ./doc
  proto.entry: proto/wtools/atop/testing/entry/Main.s
  out.raw.debug:
    path: '{path::out}/debug'
    criterion:
      debug: debug
      raw: raw
      content: prime
  out.compiled.debug:
    path: '{path::out}/compiled.debug'
    criterion:
      debug: debug
      raw: compiled
      content: prime
  out.raw.release:
    path: '{path::out}/raw.release'
    criterion:
      debug: release
      raw: raw
      content: prime
  out.compiled.release:
    path: '{path::out}/release'
    criterion:
      debug: release
      raw: compiled
      content: prime
  entry.proto.no.tests:
    path: proto/wtools/atop/testing/entry/Main.s
    criterion:
      tests: no.tests
  entry.proto.only.tests:
    path: proto/**/*.test.s
    criterion:
      tests: only.tests
  entry.out.raw.debug:
    path: '{path::out.*=1}/source/wtools/atop/testing/entry/Main.s'
    criterion:
      debug:
        - debug
        - release
      raw: raw
      content: prime
  entry.out.compiled.debug:
    path: '{path::out.*=}/source/Index.s'
    criterion:
      debug:
        - debug
        - release
      raw: compiled
      content: prime
  npm.proto.entry:
    - proto/wtools/atop/testing/entry/Main.s
    - proto/node_modules/wTesting
reflector:
  reflect.proto:
    inherit: predefined.*
    criterion:
      tests: no.tests
      debug:
        - debug
        - release
      raw:
        - raw
        - compiled
      content: prime
    filePath:
      'path::proto': '{path::out.*=1}/source'
  transpile.proto.raw:
    inherit: predefined.*
    step:
      inherit: files.transpile
      entry: 'path::entry.proto.no.tests'
    criterion:
      raw: raw
      debug: release
      content: prime
    filePath:
      'path::proto': '{path::out.raw.release}'
  transpile.proto.no.tests.compiled:
    inherit: predefined.*
    step:
      inherit: files.transpile
      entry: 'path::entry.proto.*=1'
    criterion:
      tests: no.tests
      raw: compiled
      debug:
        - debug
        - release
      content: prime
    filePath:
      '**.test*': 0
      '**.test/**': 0
      'path::proto': '{path::out.*=1}/Main.s'
  transpile.proto.only.tests.compiled:
    inherit: predefined.*
    step:
      inherit: files.transpile
      entry: 'path::entry.proto.*=1'
      external.before: '{path::out.*=1}/Main.s'
    criterion:
      tests: only.tests
      raw: compiled
      debug:
        - debug
        - release
      content: prime
    filePath:
      '**.test*': 1
      'path::proto': '{path::out.*=1}/Tests.test.s'
step:
  npm.generate:
    inherit: npm.generate
    entryPath: 'path::entry.out.*=1'
    packagePath: '{path::out.*=1}/package.json'
    filesPath: '{path::out.*=1}/source/**'
    criterion:
      debug:
        - debug
        - release
      raw:
        - raw
        - compiled
  clean.out:
    inherit: files.delete
    filePath: '{path::out.*=1}/source'
    criterion:
      debug:
        - debug
        - release
      raw:
        - raw
        - compiled
      tests:
        - no.tests
        - only.tests
      content:
        - prime
        - npm
  clean.out.npm:
    inherit: files.delete
    filePath: 'path::out.*=1'
    criterion:
      debug: debug
      raw: compiled
      tests: no.tests
      content: npm
  tst.proto:
    shell: 'tst {path::proto}'
    criterion:
      content: proto
  tst.debug:
    shell: 'tst {path::out.*=1}'
    criterion:
      content: prime
      debug: debug
  tst.release:
    shell: 'tst {path::out.*=1}'
    criterion:
      content: prime
      debug: release
build:
  debug:
    criterion:
      default: 1
      debug: debug
      raw: raw
      content: prime
    steps:
      - 'step::clean.out*=2'
      - reflect.proto.*=1
  compiled.debug:
    criterion:
      debug: debug
      raw: compiled
      content: prime
    steps:
      - 'step::clean.out*=2'
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1
  raw.release:
    criterion:
      debug: release
      raw: raw
      content: prime
    steps:
      - 'step::clean.out*=2'
      - transpile.proto.raw
  release:
    criterion:
      debug: release
      raw: compiled
      content: prime
    steps:
      - 'step::clean.out*=2'
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1
  npm:
    criterion:
      debug: debug
      raw: raw
      content: npm
    steps:
      - npm.generate.*=1
  all:
    steps:
      - 'build::debug'
      - 'build::compiled.debug'
      - 'build::raw.release'
      - 'build::release'
      - 'build::npm'
