
submodule :

  wTools :
    path : npm:///wTools
    enabled : 0
  wCopyable :
    path : npm:///wCopyable
    enabled : 0
  wpathbasic :
    path : npm:///wpathbasic
    enabled : 0
  wverbal :
    path : npm:///wverbal
    enabled : 0
  wFiles :
    path : npm:///wFiles
    enabled : 0
  wstarter :
    path : npm:///wstarter
    enabled : 0
  wcommandsaggregator :
    path : npm:///wcommandsaggregator
    enabled : 0
  wcommandsconfig :
    path : npm:///wcommandsconfig
    enabled : 0
  wstatestorage :
    path : npm:///wstatestorage
    enabled : 0
  wstatesession :
    path : npm:///wstatesession
    enabled : 0
  google-closure-compiler-js :
    path : npm:///google-closure-compiler-js#20180610.0.0
    enabled : 0
  prepack :
    path : npm:///prepack#0.2.54
    enabled : 0
  uglify-es :
    path : npm:///uglify-es#3.3.9
    enabled : 0
  babylon :
    path : npm:///babylon#6.18.0
    enabled : 0
  babel-core :
    path : npm:///babel-core#6.26.3
    enabled : 0
  babel-polyfill :
    path : npm:///babel-polyfill#6.26.0
    enabled : 0
  babel-preset-stage-0 :
    path : npm:///babel-preset-stage-0#6.24.1
    enabled : 0
  babel-preset-stage-1 :
    path : npm:///babel-preset-stage-1#6.24.1
    enabled : 0
  babel-preset-stage-2 :
    path : npm:///babel-preset-stage-2#6.24.1
    enabled : 0
  babel-preset-stage-3 :
    path : npm:///babel-preset-stage-3#6.24.1
    enabled : 0
  babel-preset-es2015 :
    path : npm:///babel-preset-es2015#6.24.1
    enabled : 0
  babel-preset-es2015-without-strict :
    path : npm:///babel-preset-es2015-without-strict#0.0.4
    enabled : 0
  babel-preset-node6-without-strict :
    path : npm:///babel-preset-node6-without-strict#0.0.1
    enabled : 0
  babel-plugin-transform-runtime :
    path : npm:///babel-plugin-transform-runtime#6.23.0
    enabled : 0
  babel-plugin-transform-class-properties :
    path : npm:///babel-plugin-transform-class-properties#6.24.1
    enabled : 0
  wtranspilationstrategy :
    path : hd://.
    enabled : 0
    criterion :
      development : 1
  wTesting :
    path : npm:///wTesting
    enabled : 0
    criterion :
      development : 1

path :

  in : '.'
  out : 'out'
  temp : 'path::out'
  proto : './proto'
  doc : './doc'

  out.raw.debug :
    path : '{path::out}/debug'
    criterion :
      debug : debug
      raw : raw
      content : prime
  out.compiled.debug :
    path : '{path::out}/compiled.debug'
    criterion :
      debug : debug
      raw : compiled
      content : prime
  out.raw.release :
    path : '{path::out}/raw.release'
    criterion :
      debug : release
      raw : raw
      content : prime
  out.compiled.release :
    path : '{path::out}/release'
    criterion :
      debug : release
      raw : compiled
      content : prime

  entry.proto.no.tests :
    path : proto/dwtools/atop/transpilationStrategy/MainBase.s
    criterion :
      tests : 'no.tests'
  entry.proto.only.tests :
    path : proto/**/*.test.s
    criterion :
      tests : 'only.tests'

  # npm.entry : proto/dwtools/abase/Layer2.s
  # npm.files : proto

  entry.out.raw.debug :
    path : '{path::out.*=1}/source/dwtools/atop/transpilationStrategy/MainBase.s'
    criterion :
      debug : [ debug, release ]
      raw : raw
      content : prime
  entry.out.compiled.debug :
    path : '{path::out.*=}/source/Index.s'
    criterion :
      debug : [ debug, release ]
      raw : compiled
      content : prime

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      tests : 'no.tests'
      debug : [ debug, release ]
      raw : [ raw, compiled ]
      content : prime
    filePath :
      path::proto : '{path::out.*=1}/source'

  transpile.proto.raw :
    inherit : predefined.*
    step :
      inherit : files.transpile
      entry : path::entry.proto.no.tests
    criterion :
      raw : raw
      debug : release
      content : prime
    filePath :
      path::proto : '{path::out.raw.release}'

  transpile.proto.no.tests.compiled :
    inherit : predefined.*
    step :
      inherit : files.transpile
      entry : path::entry.proto.*=1
    criterion :
      tests : 'no.tests'
      raw : compiled
      debug : [ debug, release ]
      content : prime
    filePath :
      '**.test*' : 0
      '**.test/**' : 0
      path::proto : '{path::out.*=1}/Main.s'

  transpile.proto.only.tests.compiled :
    inherit : predefined.*
    step :
      inherit : files.transpile
      entry : path::entry.proto.*=1
      external.before : '{path::out.*=1}/Main.s'
    criterion :
      tests : 'only.tests'
      raw : compiled
      debug : [ debug, release ]
      content : prime
    filePath :
      '**.test*' : 1
      path::proto : '{path::out.*=1}/Tests.test.s'

step :

  npm.generate :
    inherit : npm.generate
    entryPath : path::entry.out.*=1
    packagePath : '{path::out.*=1}/package.json'
    filesPath : '{path::out.*=1}/source/**'
    criterion :
      debug : [ debug, release ]
      raw : [ raw, compiled ]

  clean.out :
    inherit : files.delete
    filePath : '{path::out.*=1}/source'
    criterion :
      debug : [ debug, release ]
      raw : [ raw, compiled ]
      tests : [ 'no.tests', 'only.tests' ]
      content : [ 'prime', 'npm' ]

  clean.out.npm :
    inherit : files.delete
    filePath : path::out.*=1
    criterion :
      debug : debug
      raw : compiled
      tests : no.tests
      content : npm

  tst.proto :
    shell : 'tst {path::proto}'
    criterion :
      content : proto

  tst.debug :
    shell : 'tst {path::out.*=1}'
    criterion :
      content : prime
      debug : debug

  tst.release :
    shell : 'tst {path::out.*=1}'
    criterion :
      content : prime
      debug : release

build :

  debug :
    criterion :
      default : 1
      debug : debug
      raw : raw
      content : prime
    steps :
      - step::clean.out*=2
      - reflect.proto.*=1

  compiled.debug :
    criterion :
      debug : debug
      raw : compiled
      content : prime
    steps :
      - step::clean.out*=2
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1

  raw.release :
    criterion :
      debug : release
      raw : raw
      content : prime
    steps :
      - step::clean.out*=2
      - transpile.proto.raw

  release :
    criterion :
      debug : release
      raw : compiled
      content : prime
    steps :
      - step::clean.out*=2
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1

  npm :
    criterion :
      debug : debug
      raw : raw
      content : npm
    steps :
      - npm.generate.*=1
      # - npm.generate

  all :
    steps :
      - build::debug
      - build::compiled.debug
      - build::raw.release
      - build::release
      - build::npm
