#!/usr/bin/env node

if( typeof module !== 'undefined' )
{
  let _ = require( '../../../../wtools/Tools.s' );
  _.include( 'wProcess' );
  _.include( 'wFiles' );
}

let _ = _global_.wTools;
let shell = _.process.startPassingThrough
({
  execPath : 'debugnode',
  args : [ _.path.nativize( _.path.join( __dirname, 'Main.s' ) ) ]
});

if( typeof module !== 'undefined' )
module[ 'exports' ] = _testerGlobal_.wTools;
