#!/usr/bin/env node

if( typeof module !== 'undefined' )
{
  let _ = require( '../../../../dwtools/Tools.s' );
  _.include( 'wAppBasic' );
  _.include( 'wFiles' );
}

let _ = _global_.wTools;
let shell = _.process.startPassingThrough
({
  execPath : 'debugnode',
  args : [ _.path.nativize( _.path.join( __dirname, 'Main.s' ) ) ]
});

if( typeof module !== 'undefined' && module !== null )
module[ 'exports' ] = _global_.wTools;
