#!/usr/bin/env node

if( typeof module !== 'undefined' )
{
  let _ = require( '../../../dwtools/Tools.s' );
  _.include( 'wAppBasic' );
}

let _ = _global_.wTools;
let shell = _.process.startPassingThrough
({
  execPath : 'debugnode ' + _.path.nativize( _.path.join( __dirname, 'MainTop.s' ) ),
});

if( typeof module !== 'undefined' && module !== null )
module[ 'exports' ] = _testerGlobal_.wTools;
