#! /usr/bin/env node

if( typeof module !== 'undefined' )
{
  let _ = require( '../../Tools.s' );
  _.include( 'wAppBasic' );
}

let _ = _global_.wTools;
let o =
{
  execPath : _.path.join( __dirname, 'MainTop.s' ),
  // mode : 'shell',
}
_.process._exitHandlerRepair();
_.process.startNodePassingThrough( o );
