#! /usr/bin/env node

if( typeof module !== 'undefined' )
{
  let _ = require( '../../../../node_modules/Tools' );
  _.include( 'wProcess' );
}

const _ = _global_.wTools;
let o =
{
  execPath : _.strQuote( _.path.join( __dirname, 'Exec' ) ),
}
_.process._exitHandlerRepair();
_.process.startNjsPassingThrough( o );
